import { expect, test, type Page } from "@playwright/test";
import { loginAsTeacher, signOutTestSession } from "./helpers/auth";
import { cleanupTestData, seedTestData } from "./helpers/seed";

const apiBaseUrl = process.env.E2E_API_BASE_URL || "http://localhost:4000";

interface UnitPlanRow {
  id: number;
}

async function readJson<T>(page: Page, path: string): Promise<T> {
  const response = await page.request.get(`${apiBaseUrl}${path}`);
  if (!response.ok()) {
    throw new Error(`GET ${path} failed: ${response.status()} ${await response.text()}`);
  }
  return (await response.json()) as T;
}

test.beforeAll(async () => {
  await seedTestData();
});

test.afterAll(async () => {
  await cleanupTestData();
});

test.afterEach(async ({ page }) => {
  await signOutTestSession(page);
});

test("teacher can generate AI content and apply it to a unit plan", async ({ page }) => {
  await page.route(`${apiBaseUrl}/api/v1/ai_provider_configs`, async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify([
        {
          id: 1,
          status: "active",
        },
      ]),
    });
  });

  await page.route(`${apiBaseUrl}/api/v1/ai_task_policies`, async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify([
        {
          id: 1,
          task_type: "unit_plan",
          enabled: true,
          allowed_roles: ["teacher"],
        },
      ]),
    });
  });

  await page.route(`${apiBaseUrl}/api/v1/ai/stream`, async (route) => {
    await route.fulfill({
      status: 503,
      contentType: "application/json",
      body: JSON.stringify({ error: "stream disabled in e2e" }),
    });
  });

  await page.route(`${apiBaseUrl}/api/v1/ai_invocations`, async (route, request) => {
    if (request.method() !== "POST") {
      await route.continue();
      return;
    }

    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        id: 999,
        content: [
          "Description",
          "A student-centered unit generated by the E2E AI mock.",
          "",
          "Essential Questions",
          "- How do ratios help us compare quantities?",
          "- Where do we use fractions in everyday decisions?",
          "",
          "Enduring Understandings",
          "- Mathematical models help us reason about real situations.",
          "- Multiple representations can describe the same relationship.",
        ].join("\n"),
        provider: "mock-provider",
        model: "mock-model",
        status: "completed",
      }),
    });
  });

  await loginAsTeacher(page);

  const units = await readJson<UnitPlanRow[]>(page, "/api/v1/unit_plans");
  if (units.length === 0) {
    test.skip();
    return;
  }

  const unitId = units[0].id;
  await page.goto(`/plan/units/${unitId}`);

  await page.getByRole("button", { name: "AI Assistant" }).click();
  await expect(page.getByRole("heading", { name: "AI Assistant" })).toBeVisible();
  await expect(page.getByText("AI actions are governed by your school's policy.")).toBeVisible();

  await page
    .getByPlaceholder("Describe what you'd like the AI to help with...")
    .fill("Generate a standards-aligned unit draft for grade 6 ratios.");
  await page.getByRole("button", { name: "Generate" }).click();

  await expect(page.getByText("student-centered unit generated by the E2E AI mock")).toBeVisible();

  await page.getByRole("button", { name: "Apply" }).click();
  await expect(page.getByRole("heading", { name: "Apply AI Changes to Unit" })).toBeVisible();

  await page.getByRole("button", { name: "Confirm Apply" }).click();
  await expect(page.getByText("AI draft applied and saved as a new unit version.")).toBeVisible();
});
