name: StudentApp
options:
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.toastycaptain.k12.studentapp
    PRODUCT_NAME: StudentApp
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: K12 Student
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: >-
      UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_ASSET_PATHS: "\"\""

targets:
  StudentApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AppCore
      - path: Features
      - path: StudentApp.swift
    scheme:
      gatherCoverageData: false
      testTargets: []
