FROM ruby:4.0.1

RUN apt-get update -qq && apt-get install -y postgresql-client libyaml-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bundle", "exec", "sidekiq"]
